### ISSUE TITLE
[Bug]: Desktop app crashes on launch — simple-git declared but not packed into app.asar (workspace-hoisted build)

### ISSUE THREAD

**Issue by bambalam101** [fathah/hermes-desktop#775]
## Summary
 
On macOS, Hermes Desktop crashes on launch with a main-process uncaught exception: **`Error: Cannot find module 'simple-git'`**. The `require` originates from `app.asar/electron/git-review-ops.cjs` (pulled in by `electron/main.cjs`), and throws before any window is created.
 
`simple-git` **is** correctly declared as a production dependency in `apps/desktop/package.json` (`"simple-git": "^3.36.0"`), so this is not a missing-declaration problem. The dependency is simply absent from the packaged `app.asar` — a build/packaging defect, not a user-side corruption.
 
## Environment
 
| | |
|---|---|
| Hermes Agent version | 0.17.0 |
| Install method | Official installer (`curl … install.sh \| bash`), per-user `~/.hermes` layout |
| Update path | `hermes update` (GUI in-app update originally; reproduced via CLI) |
| OS | macOS, Apple Silicon (arm64); electron-builder reports `os=25.5.0` |
| electron-builder | 26.15.3 |
| electron | 40.10.2 |
| Node / Python | Node present; Python 3.11.15 (venv) |
 
## Steps to reproduce
 
1. Start from a previously working install and update it: `hermes update`
2. Force a clean rebuild of the desktop app: `hermes desktop --force-build`
3. Launch the packaged app (`…/release/mac-arm64/Hermes.app`)
**Result:** crash dialog — *"A JavaScript error occurred in the main process → Uncaught Exception: Error: Cannot find module 'simple-git'"*.
 
This reproduces on a **clean tree** (`git status --short` empty) and a **from-scratch** `--force-build` (electron-builder's `before-pack` removed the stale unpacked dir and repackaged), so it is not stale-build or local-state corruption.
 
## Expected vs actual
 
- **Expected:** `require('simple-git')` resolves at runtime; the app launches.
- **Actual:** main process throws immediately; the packaged `app.asar` contains no resolvable `simple-git`.
## Root cause (analysis)
 
The repo is an **npm workspace**. During packaging, electron-builder logs:
 
```
- detected workspace root for project using lock file
  pm=npm resolved=~/.hermes/hermes-agent projectDir=~/.hermes/hermes-agent/apps/desktop
```
 
`simple-git` is therefore **hoisted to the workspace-root `node_modules`** (`~/.hermes/hermes-agent/node_modules/simple-git`) rather than `apps/desktop/node_modules`. electron-builder's dependency collection for the `apps/desktop` leaf package does not pull the hoisted `simple-git` into the asar, so the declared production dependency never gets bundled.
 
This is consistent with every observed symptom:
 
- `npm install` in `apps/desktop` (and in `Resources/`) is a no-op (`up to date, 1251 packages`) — the dep already exists at the hoisted root, so there is nothing to add and nothing changes in what gets packed.
- `asarUnpack` is irrelevant here: it currently covers `**/*.node`, `**/prebuilds/**`, `dist/**`. `simple-git` is pure JS; the problem is that the package is **absent from the asar entirely**, not that it needs unpacking.
### Suggested verification
 
```bash
npx asar list \
  ~/.hermes/hermes-agent/apps/desktop/release/mac-arm64/Hermes.app/Contents/Resources/app.asar \
  | grep simple-git
```
 
Expected to return nothing on an affected build, confirming the package was not bundled.
 
## Suggested fixes (any one)
 
1. **De-hoist for the desktop package** — mark `simple-git` (and other runtime deps consumed by `electron/*.cjs`) as nohoist so they land in `apps/desktop/node_modules`, where electron-builder's collector finds them.
2. **Explicit `files` inclusion** — add the hoisted runtime deps to the electron-builder `files` glob so they're copied into the asar from the workspace root: `simple-git` plus its transitive runtime deps `@kwsites/file-exists`, `@kwsites/promise-deferred`, `debug`, `ms`.
3. **Configure hoisted-dep resolution** — ensure electron-builder resolves hoisted production dependencies for the leaf package (e.g. `includeSubNodeModules`, or equivalent dependency-collection config for the workspace layout).
A regression test asserting `simple-git` is present in the built asar (or that `git-review-ops` loads in the packaged app) would catch reintroductions.
 
## Current workaround (for affected users) — confirmed working on 0.17.0
 
Install `simple-git` and its runtime deps into `Hermes.app/Contents/Resources/node_modules` (built in an isolated dir so npm doesn't resolve to the workspace root), then ad-hoc re-sign the bundle (`hardenedRuntime: true` invalidates the signature on modification). The app then launches normally. This is **per-build** and is wiped by the next desktop rebuild/update.
 
```bash
# Build simple-git + its runtime deps where npm can't resolve to the workspace root
cd /tmp && rm -rf sgfix && mkdir sgfix && cd sgfix
npm init -y >/dev/null && npm install simple-git
 
# Copy into the app bundle where require() lands when it exits app.asar
RES=~/.hermes/hermes-agent/apps/desktop/release/mac-arm64/Hermes.app/Contents/Resources
mkdir -p "$RES/node_modules" && cp -R node_modules/. "$RES/node_modules/"
 
# Re-sign ad-hoc (hardenedRuntime) and clear quarantine
APP=~/.hermes/hermes-agent/apps/desktop/release/mac-arm64/Hermes.app
codesign --force --deep --sign - "$APP"
xattr -dr com.apple.quarantine "$APP"
open "$APP"
```
 
This patch succeeding also confirms the root cause: `simple-git` resolves fine once present in the bundle, so the only defect is that the build does not pack the workspace-hoisted copy into the asar.
 
## Evidence
 
<details>
<summary>Crash dialog stack trace</summary>
```
Uncaught Exception:
Error: Cannot find module 'simple-git'
Require stack:
- …/Hermes.app/Contents/Resources/app.asar/electron/git-review-ops.cjs
- …/Hermes.app/Contents/Resources/app.asar/electron/main.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader)
    at s._resolveFilename (node:electron/js2c/browser_init)
    at Module._load (node:internal/modules/cjs/loader)
    at Module.require (node:internal/modules/cjs/loader)
    at require (node:internal/modules/helpers)
```
</details>
<details>
<summary>Clean rebuild log (abridged) — reproduces on a from-scratch build</summary>
```
$ hermes update
→ Found 2 new commit(s)
→ Pulling updates...
✓ Update complete!   (git status --short → clean afterward)
 
$ hermes desktop --force-build
→ Installing desktop workspace dependencies...
  added 1244 packages, audited 1251 packages
→ Building desktop packaged app...
  • electron-builder version=26.15.3
  • detected workspace root … resolved=~/.hermes/hermes-agent  projectDir=…/apps/desktop
  [before-pack] removed stale unpacked dir before staging: …/release/mac-arm64
  • packaging  platform=darwin arch=arm64 electron=40.10.2
  …/Hermes.app: replacing existing signature
→ Launching packaged Hermes Desktop …
```
 
`apps/desktop/package.json` confirms the declaration: `"simple-git": "^3.36.0"` under `dependencies`.
</details>
